package com.zhognong.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zhognong.domain.CNCatalog;
import com.zhognong.domain.CNCourse;
import com.zhognong.domain.CNUser;

import com.zhognong.dao.CNCatalogDao;
import com.zhognong.dao.CNCourseDao;
import com.zhognong.dao.CNUserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cNCatalogDaoConfig;
    private final DaoConfig cNCourseDaoConfig;
    private final DaoConfig cNUserDaoConfig;

    private final CNCatalogDao cNCatalogDao;
    private final CNCourseDao cNCourseDao;
    private final CNUserDao cNUserDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cNCatalogDaoConfig = daoConfigMap.get(CNCatalogDao.class).clone();
        cNCatalogDaoConfig.initIdentityScope(type);

        cNCourseDaoConfig = daoConfigMap.get(CNCourseDao.class).clone();
        cNCourseDaoConfig.initIdentityScope(type);

        cNUserDaoConfig = daoConfigMap.get(CNUserDao.class).clone();
        cNUserDaoConfig.initIdentityScope(type);

        cNCatalogDao = new CNCatalogDao(cNCatalogDaoConfig, this);
        cNCourseDao = new CNCourseDao(cNCourseDaoConfig, this);
        cNUserDao = new CNUserDao(cNUserDaoConfig, this);

        registerDao(CNCatalog.class, cNCatalogDao);
        registerDao(CNCourse.class, cNCourseDao);
        registerDao(CNUser.class, cNUserDao);
    }
    
    public void clear() {
        cNCatalogDaoConfig.clearIdentityScope();
        cNCourseDaoConfig.clearIdentityScope();
        cNUserDaoConfig.clearIdentityScope();
    }

    public CNCatalogDao getCNCatalogDao() {
        return cNCatalogDao;
    }

    public CNCourseDao getCNCourseDao() {
        return cNCourseDao;
    }

    public CNUserDao getCNUserDao() {
        return cNUserDao;
    }

}
