package com.zhognong.utils;

/**
 * Created by Administrator on 2017/3/30.
 */
public class JsonDemo {
    public static final String JSONDEMO="{\"root\":\"TestData\", \"dir_type\":\"0\", \"sub_node\":[\n" +
            "                                 {\"node_name\":\"中公网校面试辅导系列课程\",\n" +
            "                                   \"dir_type\":\"0\",\n" +
            "                                   \"sub_node\":[{\"node_name\":\"2017年上海市考面试课程\",\n" +
            "                                                   \"dir_type\":\"1\",\n" +
            "                                                   \"sub_node\":[{\"node_name\":\"24课时1对6\",\n" +
            "                                                                   \"node_type\":\"0\",\n" +
            "                                                                   \"sub_node\":[]}]}]},\n" +
            "                                 {\"node_name\":\"中公网校农信社辅导课程\",\n" +
            "                                   \"dir_type\":\"0\",\n" +
            "                                   \"sub_node\":[{\"node_name\":\"2016广西农商行笔试辅导课程\",\n" +
            "                                                   \"dir_type\":\"0\",\n" +
            "                                                   \"sub_node\":[{\"node_name\":\"系统精讲班\",\n" +
            "                                                                   \"dir_type\":\"1\",\n" +
            "                                                                   \"sub_node\":[{\"node_name\":\"计算机\",\n" +
            "                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                   \"node_type\":\"0\",\n" +
            "                                                                                   \"sub_node\":[]},\n" +
            "                                                                                 {\"node_name\":\"公基\",\n" +
            "                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                   \"node_type\":\"1\",\n" +
            "                                                                                   \"sub_node\":[]},\n" +
            "                                                                                 {\"node_name\":\"行测\",\n" +
            "                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                   \"node_type\":\"2\",\n" +
            "                                                                                   \"sub_node\":[]},\n" +
            "                                                                                 {\"node_name\":\"金融\",\n" +
            "                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                   \"node_type\":\"0\",\n" +
            "                                                                                   \"sub_node\":[]},\n" +
            "                                                                                 {\"node_name\":\"经济\",\n" +
            "                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                   \"node_type\":\"1\",\n" +
            "                                                                                   \"sub_node\":[]},\n" +
            "                                                                                 {\"node_name\":\"会计\",\n" +
            "                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                   \"node_type\":\"2\",\n" +
            "                                                                                   \"sub_node\":[]}]}]}]},\n" +
            "                                 {\"node_name\":\"测试非卖课程\",\n" +
            "                                   \"dir_type\":\"0\",\n" +
            "                                   \"sub_node\":[{\"node_name\":\"2017天津私享课\",\n" +
            "                                                   \"dir_type\":\"0\",\n" +
            "                                                   \"sub_node\":[{\"node_name\":\"系统精讲班《行测》\",\n" +
            "                                                                   \"dir_type\":\"1\",\n" +
            "                                                                   \"sub_node\":[{\"node_name\":\"第一阶段\",\n" +
            "                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                   \"sub_node\":[{\"node_name\":\"第一部分\",\n" +
            "                                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                                   \"node_type\":\"2\",\n" +
            "                                                                                                   \"sub_node\":[]}]}]}]}]},\n" +
            "                                 {\"node_name\":\"中公网校名师课程\",\n" +
            "                                   \"dir_type\":\"0\",\n" +
            "                                   \"sub_node\":[{\"node_name\":\"2017省考零基础入门突进班\",\n" +
            "                                                   \"dir_type\":\"0\",\n" +
            "                                                   \"sub_node\":[{\"node_name\":\"2017贵州省考零基础入门突破班\",\n" +
            "                                                                   \"dir_type\":\"1\",\n" +
            "                                                                   \"sub_node\":[{\"node_name\":\"行测\",\n" +
            "                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                   \"node_type\":\"0\",\n" +
            "                                                                                   \"sub_node\":[]},\n" +
            "                                                                                 {\"node_name\":\"申论\",\n" +
            "                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                   \"node_type\":\"1\",\n" +
            "                                                                                   \"sub_node\":[]},\n" +
            "                                                                                 {\"node_name\":\"报名后请加QQ群8888888\",\n" +
            "                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                   \"node_type\":\"2\",\n" +
            "                                                                                   \"sub_node\":[]}]}]}]},\n" +
            "                                 {\"node_name\":\"2017公务员考试辅导课程\",\n" +
            "                                   \"dir_type\":\"0\",\n" +
            "                                   \"sub_node\":[{\"node_name\":\"2017年安徽省公务员考试\",\n" +
            "                                                   \"dir_type\":\"0\",\n" +
            "                                                   \"sub_node\":[{\"node_name\":\"高分专项班\",\n" +
            "                                                                   \"dir_type\":\"1\",\n" +
            "                                                                   \"sub_node\":[{\"node_name\":\"申论\",\n" +
            "                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                   \"node_type\":\"0\",\n" +
            "                                                                                   \"sub_node\":[]},\n" +
            "                                                                                 {\"node_name\":\"行测\",\n" +
            "                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                   \"sub_node\":[{\"node_name\":\"数量关系\",\n" +
            "                                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                                   \"node_type\":\"1\",\n" +
            "                                                                                                   \"sub_node\":[]},\n" +
            "                                                                                                 {\"node_name\":\"判断推理\",\n" +
            "                                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                                   \"node_type\":\"1\",\n" +
            "                                                                                                   \"sub_node\":[]},\n" +
            "                                                                                                 {\"node_name\":\"资料分析\",\n" +
            "                                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                                   \"sub_node\":[]},\n" +
            "                                                                                                 {\"node_name\":\"言语理解\",\n" +
            "                                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                                   \"node_type\":\"1\",\n" +
            "                                                                                                   \"sub_node\":[]},\n" +
            "                                                                                                 {\"node_name\":\"常识判断\",\n" +
            "                                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                                   \"node_type\":\"1\",\n" +
            "                                                                                                   \"sub_node\":[]}]}]}]},\n" +
            "                                                 {\"node_name\":\"2017年深圳市公务员考试\",\n" +
            "                                                   \"dir_type\":\"0\",\n" +
            "                                                   \"sub_node\":[{\"node_name\":\"高分专项班\",\n" +
            "                                                                   \"dir_type\":\"1\",\n" +
            "                                                                   \"node_type\":\"0\",\n" +
            "                                                                   \"sub_node\":[{\"node_name\":\"申论\",\n" +
            "                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                   \"node_type\":\"0\",\n" +
            "                                                                                   \"sub_node\":[]},\n" +
            "                                                                                 {\"node_name\":\"行测\",\n" +
            "                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                   \"sub_node\":[{\"node_name\":\"数量关系\",\n" +
            "                                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                                   \"node_type\":\"1\",\n" +
            "                                                                                                   \"sub_node\":[]},\n" +
            "                                                                                                 {\"node_name\":\"判断推理\",\n" +
            "                                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                                   \"node_type\":\"1\",\n" +
            "                                                                                                   \"sub_node\":[]},\n" +
            "                                                                                                 {\"node_name\":\"资料分析\",\n" +
            "                                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                                   \"node_type\":\"1\",\n" +
            "                                                                                                   \"sub_node\":[]},\n" +
            "                                                                                                 {\"node_name\":\"言语理解\",\n" +
            "                                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                                   \"node_type\":\"1\",\n" +
            "                                                                                                   \"sub_node\":[]},\n" +
            "                                                                                                 {\"node_name\":\"常识判断\",\n" +
            "                                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                                   \"node_type\":\"1\",\n" +
            "                                                                                                   \"sub_node\":[]}]}]}]},\n" +
            "                                                 {\"node_name\":\"2017年贵州公务员课程\",\n" +
            "                                                   \"dir_type\":\"0\",\n" +
            "                                                   \"sub_node\":[{\"node_name\":\"高分专项班\",\n" +
            "                                                                   \"dir_type\":\"1\",\n" +
            "                                                                   \"node_type\":\"0\",\n" +
            "                                                                   \"sub_node\":[{\"node_name\":\"申论\",\n" +
            "                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                   \"node_type\":\"0\",\n" +
            "                                                                                   \"sub_node\":[]},\n" +
            "                                                                                 {\"node_name\":\"行测\",\n" +
            "                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                   \"sub_node\":[{\"node_name\":\"数量关系\",\n" +
            "                                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                                   \"node_type\":\"1\",\n" +
            "                                                                                                   \"sub_node\":[]},\n" +
            "                                                                                                 {\"node_name\":\"判断推理\",\n" +
            "                                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                                   \"node_type\":\"1\",\n" +
            "                                                                                                   \"sub_node\":[]},\n" +
            "                                                                                                 {\"node_name\":\"资料分析\",\n" +
            "                                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                                   \"node_type\":\"1\",\n" +
            "                                                                                                   \"sub_node\":[]},\n" +
            "                                                                                                 {\"node_name\":\"言语理解\",\n" +
            "                                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                                   \"node_type\":\"1\",\n" +
            "                                                                                                   \"sub_node\":[]},\n" +
            "                                                                                                 {\"node_name\":\"常识判断\",\n" +
            "                                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                                   \"node_type\":\"1\",\n" +
            "                                                                                                   \"sub_node\":[]}]}]}]},\n" +
            "                                                 {\"node_name\":\"2017年浙江省考私享课\",\n" +
            "                                                   \"dir_type\":\"0\",\n" +
            "                                                   \"sub_node\":[{\"node_name\":\"高分专项班\",\n" +
            "                                                                   \"dir_type\":\"1\",\n" +
            "                                                                   \"node_type\":\"0\",\n" +
            "                                                                   \"sub_node\":[{\"node_name\":\"申论\",\n" +
            "                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                   \"node_type\":\"0\",\n" +
            "                                                                                   \"sub_node\":[]},\n" +
            "                                                                                 {\"node_name\":\"行测\",\n" +
            "                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                   \"sub_node\":[{\"node_name\":\"数量关系\",\n" +
            "                                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                                   \"node_type\":\"1\",\n" +
            "                                                                                                   \"sub_node\":[]},\n" +
            "                                                                                                 {\"node_name\":\"判断推理\",\n" +
            "                                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                                   \"node_type\":\"1\",\n" +
            "                                                                                                   \"sub_node\":[]},\n" +
            "                                                                                                 {\"node_name\":\"资料分析\",\n" +
            "                                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                                   \"node_type\":\"1\",\n" +
            "                                                                                                   \"sub_node\":[]},\n" +
            "                                                                                                 {\"node_name\":\"言语理解\",\n" +
            "                                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                                   \"node_type\":\"1\",\n" +
            "                                                                                                   \"sub_node\":[]},\n" +
            "                                                                                                 {\"node_name\":\"常识判断\",\n" +
            "                                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                                   \"node_type\":\"1\",\n" +
            "                                                                                                   \"sub_node\":[]}]}]}]},\n" +
            "                                                 {\"node_name\":\"公务员考试私享课堂\",\n" +
            "                                                   \"dir_type\":\"0\",\n" +
            "                                                   \"sub_node\":[{\"node_name\":\"高分专项班\",\n" +
            "                                                                   \"dir_type\":\"1\",\n" +
            "                                                                   \"node_type\":\"0\",\n" +
            "                                                                   \"sub_node\":[{\"node_name\":\"申论\",\n" +
            "                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                   \"node_type\":\"0\",\n" +
            "                                                                                   \"sub_node\":[]},\n" +
            "                                                                                 {\"node_name\":\"行测\",\n" +
            "                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                   \"sub_node\":[{\"node_name\":\"数量关系\",\n" +
            "                                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                                   \"node_type\":\"1\",\n" +
            "                                                                                                   \"sub_node\":[]},\n" +
            "                                                                                                 {\"node_name\":\"判断推理\",\n" +
            "                                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                                   \"node_type\":\"1\",\n" +
            "                                                                                                   \"sub_node\":[]},\n" +
            "                                                                                                 {\"node_name\":\"资料分析\",\n" +
            "                                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                                   \"node_type\":\"1\",\n" +
            "                                                                                                   \"sub_node\":[]},\n" +
            "                                                                                                 {\"node_name\":\"言语理解\",\n" +
            "                                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                                   \"node_type\":\"1\",\n" +
            "                                                                                                   \"sub_node\":[]},\n" +
            "                                                                                                 {\"node_name\":\"常识判断\",\n" +
            "                                                                                                   \"dir_type\":\"0\",\n" +
            "                                                                                                   \"node_type\":\"1\",\n" +
            "                                                                                                   \"sub_node\":[]}]}]}]}\n" +
            "                                                 ]},\n" +
            "                                 {\"node_name\":\"2017教师招聘中公网校课程\",\n" +
            "                                   \"dir_type\":\"0\",\n" +
            "                                   \"sub_node\":[{\"node_name\":\"辽宁\",\n" +
            "                                                   \"dir_type\":\"1\",\n" +
            "                                                   \"sub_node\":[{\"node_name\":\"#教育基础知识\",\n" +
            "                                                                   \"dir_type\":\"0\",\n" +
            "                                                                   \"node_type\":\"2\",\n" +
            "                                                                   \"sub_node\":[]}]}]},\n" +
            "                                 {\"node_name\":\"2017中公网校事业单位辅导课程\",\n" +
            "                                   \"dir_type\":\"0\",\n" +
            "                                   \"sub_node\":[\n" +
            "                                           {\"node_name\":\"江苏\",\n" +
            "                                             \"dir_type\":\"1\",\n" +
            "                                             \"sub_node\":[{\"node_name\":\"统考\",\n" +
            "                                                             \"dir_type\":\"0\",\n" +
            "                                                             \"node_type\":\"0\",\n" +
            "                                                             \"sub_node\":[]}]},\n" +
            "                                           {\"node_name\":\"陕西\",\n" +
            "                                             \"dir_type\":\"0\",\n" +
            "                                             \"node_type\":\"2\",\n" +
            "                                             \"sub_node\":[]}\n" +
            "                                           ]}\n" +
            "                                 ]}";
}
